# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kannister < Formula
  desc "Homebrew installer for kannister-cli."
  homepage "https://github.com/kannister-app/homebrew-kannister"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Darwin_x86_64.tar.gz"
      sha256 "776828b9106dadaf1d60688d74c7daaacbbaf796b72321eb55ca9e46049bb3f7"

      def install
        bin.install "kannister"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Darwin_arm64.tar.gz"
      sha256 "82ec128ba4ad6b652a2c4ce698b972443a6352aa1636fefa988abe60608745bf"

      def install
        bin.install "kannister"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Linux_arm64.tar.gz"
      sha256 "f1c9056a3e70e116b90e63a6862d61f6d27b9bf560b32a375eeb930992ecd8cc"

      def install
        bin.install "kannister"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Linux_x86_64.tar.gz"
      sha256 "b0290b67c010f76e48d257e8f2b1fa92425d4387d2c6a91032a4ce0f8591c9ef"

      def install
        bin.install "kannister"
      end
    end
  end
end
