# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kannister < Formula
  desc "Homebrew installer for kannister-cli."
  homepage "https://github.com/kannister-app/homebrew-kannister"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Darwin_arm64.tar.gz"
      sha256 "1b44739f1be1fc88bfea800505660ff47f4bdb0bb863a67a406b901f9ddb1769"

      def install
        bin.install "kannister-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Darwin_x86_64.tar.gz"
      sha256 "5ec0ee2a7f1d616beedb9cca39c60a89897991bd2722bb5bc78b359978d36b94"

      def install
        bin.install "kannister-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Linux_arm64.tar.gz"
      sha256 "c669c30c6e967f55912334ce81144a81178abe84b5d5c18d508491c622421ab7"

      def install
        bin.install "kannister-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kannister-app/kannister-cli/releases/download/v0.0.1/kannister-cli_Linux_x86_64.tar.gz"
      sha256 "5ba887f5b2f4155e1a2c4a4f77fee71bd31bbabb239d4d196971d2c8a4d9d1ab"

      def install
        bin.install "kannister-cli"
      end
    end
  end
end
